import { Check, Eye, Filter, MessageSquareWarning } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header";
import { SectionCard } from "@/components/shared/section-card";
import { ContentStatusBadge } from "@/components/shared/content-status-badge";
import { recentContents } from "@/data/mock-data";

export default function EditorialPage() {
  return <div><PageHeader eyebrow="Governança de conteúdo" title="Gestão Editorial" description="Acompanhe a fila editorial, faça revisões e registre decisões de aprovação." actions={<button className="secondary-button"><Filter size={16} />Filtrar fila</button>} /><div className="mb-5 grid gap-4 sm:grid-cols-3"><div className="surface-card p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Para revisar</p><p className="mt-2 text-3xl font-bold text-slate-900">07</p></div><div className="surface-card p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Com ajustes</p><p className="mt-2 text-3xl font-bold text-rose-700">05</p></div><div className="surface-card p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Aprovados no mês</p><p className="mt-2 text-3xl font-bold text-blue-700">31</p></div></div><SectionCard title="Fila de conteúdos" description="Ações demonstrativas — nenhuma decisão será persistida nesta sprint"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead><tr className="bg-slate-50 text-[10px] font-bold uppercase tracking-wider text-slate-500"><th className="px-6 py-3">Conteúdo</th><th className="px-4 py-3">Responsável</th><th className="px-4 py-3">Data</th><th className="px-4 py-3">Status</th><th className="px-6 py-3 text-right">Decisão</th></tr></thead><tbody>{recentContents.map(item => <tr key={item.id} className="border-t border-slate-100"><td className="px-6 py-4"><p className="font-bold text-slate-800">{item.title}</p><p className="mt-1 text-xs text-slate-400">{item.category} · {item.id}</p></td><td className="px-4 py-4 text-sm text-slate-600">{item.owner}</td><td className="px-4 py-4 text-sm text-slate-500">{item.date}</td><td className="px-4 py-4"><ContentStatusBadge status={item.status} /></td><td className="px-6 py-4"><div className="flex justify-end gap-2"><button title="Visualizar" className="secondary-button px-3"><Eye size={15} /></button><button title="Solicitar ajustes" className="secondary-button px-3 text-rose-700"><MessageSquareWarning size={15} /></button><button title="Aprovar" className="primary-button px-3"><Check size={15} /></button></div></td></tr>)}</tbody></table></div></SectionCard></div>;
}
